name: Scheduled Clean-Up

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 1 * *' # runs ones every month to avoid costs but should be run more often

jobs:
    cleanUp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
               node-version: '20'

            - name: Install dependencies
              run: npm ci
              working-directory: .github/scripts

            - name: Run cleanup script
              run: node .github/scripts/cleanUp.js
              env:
                MONGODB_URI: ${{ secrets.MONGODB_URI }}
                CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
                CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
                CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
                DRY_RUN: false
                LOG_LEVEL: info



